use diesel_migrations::{embed_migrations, EmbeddedMigrations};

// Need to use this for because schema.rs uses the macros and is autogenerated
#[macro_use]
extern crate diesel;

// for parquet_derive
extern crate canonical_json;
extern crate parquet;
extern crate parquet_derive;

pub mod config;
pub mod db;
pub mod parquet_processors;
pub mod processors;
#[path = "db/schema.rs"]
pub mod schema;
pub mod utils;

pub const MIGRATIONS: EmbeddedMigrations = embed_migrations!("./src/db/migrations");
